/*
 * RiceChecks
 * Copyright (c) 2019, Dan S. Wallach, Rice University
 * Available subject to the Apache 2.0 License
 */

package edu.rice.autograder

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.MapperFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.xml.JacksonXmlModule
import com.fasterxml.jackson.dataformat.xml.XmlMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

//
// Jackson has these ObjectMapper things that are used both to serialize and
// deserialize. We create and configure them here.
//

private fun ObjectMapper.setup() =
    this.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .registerKotlinModule()

val yamlHeader = "# THIS FILE IS AUTOMATICALLY GENERATED (%s), DO NOT EDIT!\n".format(
    ZonedDateTime.now(ZoneId.systemDefault())
        .format(DateTimeFormatter.RFC_1123_DATE_TIME)
)

/** General-purpose Jackson YAML mapper. */
val jacksonYamlMapper = YAMLMapper().setup()

/** General-purpose Jackson XML mapper. */
val jacksonXmlMapper: ObjectMapper = XmlMapper(
    JacksonXmlModule().apply {
        setDefaultUseWrapper(false)
    }
).setup()

/** General-purpose Jackson JSON mapper. */
val jacksonJsonMapper: ObjectMapper = ObjectMapper().setup()
