name: RiceChecks Autograder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java18
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew --console=plain --no-parallel --max-workers=1 --no-daemon :autograder:check autograder
